"""Shared parser constants."""

RN_CODES = {"317N", "317W", "3178", "8536"}
PSA_CODES = {"5001", "5056", "5057"}
EXCLUDED_JOB_CODES = {"4120"}
KNOWN_JOB_CODES = RN_CODES | PSA_CODES | EXCLUDED_JOB_CODES

CLINICAL_LEADER_CODE = "8536"
LEAD_PAY_CODES = {"LP", "LP - LEAD PAY", "LEAD PAY"}

ROLE_RN = "RN"
ROLE_PSA = "PSA"
ROLE_OTHER = "OTHER"

SHIFT_DAY = "DAY"
SHIFT_NIGHT = "NIGHT"
